# IP and port the flint server should bind to
ip = "127.0.0.1"
port = 25565

# Available message placeholders:
#
#   %h  Host that the client connected to
#   %n  Name of the upstream the client connected to (if matching)
#   %a  Address of the upstream the client connected to (if matching)
[messages]
server_not_found = "§4No Minecraft server running at §c%h"
server_down = "§c%n§4 is currently offline"
maintenance = "§c%n§4 is in maintenance mode"

[[upstream]]
name = "Example Server"         # Server name
host = "localhost"              # The server that the client should connect to
address = "example.com:25565"   # Address of the upstream server